name: Extract SPIFFS Binary

on:
  push:
    paths:
      - 'spiffs.bin'  # Trigger only when this file is uploaded or updated

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download mkspiffs tool
        run: |
          curl -LO https://github.com/igrr/mkspiffs/releases/download/0.2.3/mkspiffs-0.2.3-arduino-esp32-linux64.tar.gz
          tar -xzf mkspiffs-0.2.3-arduino-esp32-linux64.tar.gz
          chmod +x mkspiffs-0.2.3-arduino-esp32-linux64/mkspiffs

      - name: Extract SPIFFS contents
        run: |
          mkdir -p extracted_files
          ./mkspiffs-0.2.3-arduino-esp32-linux64/mkspiffs -u extracted_files -b 4096 -p 256 -s 0x170000 spiffs.bin

      - name: List extracted files
        run: ls -R extracted_files

      - name: Upload extracted files
        uses: actions/upload-artifact@v4
        with:
          name: extracted-spiffs
          path: extracted_files/**
